version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ssshesh_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ssshesh

volumes:
  mongo_data: